/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacyy;

/**
 *
 * @author mohsi
 */
//import pharmacyy.AddMedicine;
//import Sell_Product.Sell_Product;
//import View_Product.View_Product;
//import bill.bill;

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        view_product = new javax.swing.JButton();
        add_product = new javax.swing.JButton();
        sell_product = new javax.swing.JButton();
        view_receipt = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 832, -1));

        view_product.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        view_product.setText("View Inventory");
        view_product.setActionCommand("View Receipt");
        view_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_productActionPerformed(evt);
            }
        });
        getContentPane().add(view_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 260, 100));

        add_product.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        add_product.setText("Add Product");
        add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_productActionPerformed(evt);
            }
        });
        getContentPane().add(add_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 260, 100));

        sell_product.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        sell_product.setText("Sell Product");
        sell_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_productActionPerformed(evt);
            }
        });
        getContentPane().add(sell_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 110));

        view_receipt.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        view_receipt.setText("Add Customer Info");
        view_receipt.setActionCommand(" Product");
        view_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_receiptActionPerformed(evt);
            }
        });
        getContentPane().add(view_receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 228, 260, 110));

        exit.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 228, 260, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void view_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_productActionPerformed
        // TODO add your handling code here:
        ViewMedicine ViewProductFrame = new ViewMedicine();

    // Set the Add_medicine frame visible
    ViewProductFrame.setVisible(true);

    // Set the Dashboard frame invisible
    this.setVisible(false);
    }//GEN-LAST:event_view_productActionPerformed

    private void add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_productActionPerformed
                // TODO add your handling code here:
       AddMedicine addMedicineFrame = new AddMedicine();

    // Set the Add_medicine frame visible
    addMedicineFrame.setVisible(true);

    // Set the Dashboard frame invisible
    this.setVisible(false);
                
    }//GEN-LAST:event_add_productActionPerformed

    private void sell_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_productActionPerformed
        // TODO add your handling code here:
         SellMedicine sellproductframe = new SellMedicine();

    // Set the Add_medicine frame visible
    sellproductframe.setVisible(true);

    // Set the Dashboard frame invisible
    this.setVisible(false);
    }//GEN-LAST:event_sell_productActionPerformed

    private void view_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_receiptActionPerformed
        // TODO add your handling code here:
       AddUser user1 = new AddUser();
       user1.setVisible(true);

       this.setVisible(false);
    }//GEN-LAST:event_view_receiptActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_product;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sell_product;
    private javax.swing.JButton view_product;
    private javax.swing.JButton view_receipt;
    // End of variables declaration//GEN-END:variables
}
